### ISSUE TITLE
remove dynamically loading of services

### ISSUE THREAD

**Issue by KaiserKarel** [ArkEcosystem/python-client#53]
**Is your feature request related to a problem? Please describe.**

Currently services are dynamically loaded during construction of the client through the `_import_api` method. This adds extra magic in the lib, without providing concrete benefits (I suspect it does not even save LOCs). IDE's are unable to autocomplete methods; and some students at hackathons are actually using `Connection` object to manually format requests.

**Describe the solution you'd like**
Remove magic constructors and explicitly construct the different services.

**Comment by roks0n** [comment]
We can (and should) remove functionality of the `_import_api` when v1 is entirely deprecated and removed, until then we can not do it if we want to have the similar logic of calling methods as other client libraries.

> IDE's are unable to autocomplete methods

I don't feel this is a valid argument as to why we should move away from `_import_lib`, `_import_lib` is there for a reason so that you use the same methods for v1 and v2 and don't have to import `client.two`, `client.one` paths and makes it so there's only one entrypoint into the client

**Comment by faustbrian** [comment]
As @roks0n already said, those methods exists in all clients for a reason as we have to support v1 for another few months.

Simply removing things because some editor or IDE isn't able to handle it isn't really an argument why something is bad. Also if the students have issues understanding "magic methods" that is a chance to learn about them and why they sometimes are useful.

Once the v1 API is removed in 2.1 those methods will also disappear so it will stay like that for a few months.

**Comment by KaiserKarel** [comment]
So imho, now we have a client implicitly doing lots of stuff, no type hints (which are also made impossible by the _import_api(), or maybe not when usig union types) for the sake of managing the same style across clients. Would it instead be more logical to say within the standards of the programming language?

I get that fixing this now would lead to a breaking API change, but why we did not choose to handle this like: `from ark.v2 import ArkClient` seems like a mistake to me. It is not about IDE support, but magic methods being bad in general.

Would also be nice if discussion issues  weren't closed until the discussion comes to an end, based-god @faustbrian, even if we are not changing the client.

It is definitely a style thing, where I try to use python as typed-as-possible. This way works, but combine this with the short documentation and you are asking for people to get confused.

**Comment by roks0n** [comment]
https://www.youtube.com/watch?v=rrBJVMyD-Gs&feature=youtu.be&t=2065

**Comment by KaiserKarel** [comment]
They help with figuring out what a function wants. Currently the Create API accepts a transactions argument:

```
def create(self, transactions):
        return self.request_post('transactions', data={'transactions': transactions})
```

how is a user supposed to figure out what a transactions is? If it were properly documented... However I agree on type hints being executed poorly. I have been programming mainly in typed languages the last year, so coming back to python was quite difficult.

**Comment by roks0n** [comment]
Type hints wouldn't help user to figure this out. I agree, documentation should be improved.

**Comment by KaiserKarel** [comment]
They would, as they would define that it is a list; and what object is accepted.

**Comment by roks0n** [comment]
No, `transactions` refers to a list. Devs would still have issues with knowing how transaction object (actually a dict) should be structured.

I don't agree with the statement that the client is difficult, but I agree that more documentation should be written and perhaps more examples of how crypto library should be used along with the client.

**Comment by KaiserKarel** [comment]
The client itself is not difficult, but as someone not having worked with it before; it definitely takes a while to figure out. A transaction could have been expressed as a NamedTuple, data class or full class. structs can be emulated like so:

```python
class Bunch:
    def __init__(self, **kwds):
        self.__dict__.update(kwds)
```

if memory is a concern, __slots__ or data classes are valid too. But correct documentation is better ofc.

**Comment by KaiserKarel** [comment]
But as a P.S. I mean no disrespect. It is still a good client. :) No product is improved by compliments.

**Comment by roks0n** [comment]
Oh, no hard feelings at all, I'm not even the one who wrote the actual client, I'm just expressing my opinion based on my own personal experience to date.

Regarding structs, crypto lib does that, hence why I suggested we should have a place in the docs how to use both. :)

I'm afraid to make a promise that I'll write an article or add the docs anytime soon due to my current time constraints, but in case I clear my schedule and no one else does it beforehand I'll gladly do it.

**Comment by KaiserKarel** [comment]
worked with the v1 clients a bit; this one I definitely prefer. Especially examples on the other transaction types would be great. I am quite busy as well; will see if I can make a PR later on.
